export const positions = [
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "successful",
    Time: "09:35",
    Type: "B",
    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "pending",
    Time: "09:35",
    Type: "B",
    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "pending",
    Time: "09:35",
    Type: "B",
    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "successful",
    Time: "09:35",
    Type: "B",

    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "successful",
    Time: "09:35",
    Type: "B",
    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
  {
    name: "AppleInc 28 Jan 50 Call",
    status: "successful",
    Time: "09:35",
    Type: "B",
    Qty: 75,
    value: 75,
    CMP: 22.1,
    price: 30.0,
  },
];
